### ISSUE TITLE
Can not attach Medium to new created Machine

### ISSUE THREAD

**Issue by brean** [mjdorma/pyvbox#105]
##### ENVIRONMENT
- Operating System: Windows 10.0.16299.192
- Python version: 3.6.3
- VirtualBox version: 5.2.4 r119785
- VirtualBox SDK version: 5.2.4 r119785
- pyvbox version: 1.2.0
- [ ] Happens in latest `master` branch?

##### SUMMARY
I want to create a whole VM from scratch using just python, I don't know how/when to create my medium. When I run attach_device before I register the machine I get "0x80020009 (Cannot attach storage devices to an unregistered machine)" and when I run it after register_machine I get the error message "0x80020009 (The machine is not mutable or running (state is PoweredOff))" although I create and lock a session.

##### STEPS TO REPRODUCE
Create a new machine, attach storage controller and call machine.attach_device. For my exact code take a look at [this](https://gist.github.com/brean/2cb350b9a3997a738674df4ea75d2258) as well as [this config](https://gist.github.com/brean/f18b506a1ee29fb0eb9c2e41833005b9)

##### EXPECTED RESULTS
I should be able to attach the device somehow either before or after I register the machine.

##### ACTUAL RESULTS
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\virtualbox\library_base.py", line 195, in _call_method
    ret = method(*in_params)
  File "C:\Users\user\AppData\Local\Temp\gen_py\3.6\D7569351-1750-46F0-936E-BD127D5BC264x0x1x3.py", line 4937, in AttachDevice
    , aControllerPort, aDevice, aType, aMedium)
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'MachineWrap', 'The machine is not mutable or running (state is PoweredOff)', None, 0, -2135228414), None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "install_xenial_virtualbox.py", line 92, in <module>
    main()
  File "install_xenial_virtualbox.py", line 88, in main
    install(**config)
  File "install_xenial_virtualbox.py", line 73, in install
    attach_device(machine=machine, port=port, **m)
  File "install_xenial_virtualbox.py", line 32, in attach_device
    machine.attach_device(name, port, 0, device_type, om)
  File "C:\ProgramData\Anaconda3\lib\site-packages\virtualbox\library.py", line 11289, in attach_device
    in_p=[name, controller_port, device, type_p, medium])
  File "C:\ProgramData\Anaconda3\lib\site-packages\virtualbox\library_base.py", line 186, in _call
    return self._call_method(method, in_p=in_p)
  File "C:\ProgramData\Anaconda3\lib\site-packages\virtualbox\library_base.py", line 213, in _call_method
    raise errobj
virtualbox.library_base.VBoxError: 0x80020009 (The machine is not mutable or running (state is PoweredOff))
```

**Comment by SethMichaelLarson** [comment]
Have you tried calling the methods on `session.machine` instead of `machine`?

**Comment by SethMichaelLarson** [comment]
Also have you tried `create_session(LockType.write)`?

**Comment by brean** [comment]
I tried `create_session(LockType.write)` which did not work but using `session.machine` instead of `machine` did the trick. Thank you very much!

**Comment by SethMichaelLarson** [comment]
I'm glad I was able to help. :)

**Comment by vipullinux** [comment]
And what's the trick? Would you mind sharing with us?
