### ISSUE TITLE
Can't start guest session on new VirtualBox (ValueError: Can not find enumeration where value=None).

### ISSUE THREAD

**Issue by shohamp** [mjdorma/pyvbox#31]
Like issue #14. Only I have new VirtualBox and pyvbox:
Ubuntu 14.04.01 LTS x64
VirtualBox 4.3.18 r96516
python 2.7.6
pyvbox new from repository (2da4fba4ba1c5cb9bc9e829d869df7343f2b077c)

This code:
```python
import virtualbox
vbox = virtualbox.VirtualBox()
m = vbox.machines[0]
s = m.create_session()
s.console.guest.create_session('beta', 'beta')
```

results in the next backtrace:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyvbox-0.2.0-py2.7.egg/virtualbox/library_ext/guest.py", line 20, in create_session
    if session.status == library.GuestSessionStatus.started:
  File "/usr/local/lib/python2.7/dist-packages/pyvbox-0.2.0-py2.7.egg/virtualbox/library.py", line 15821, in status
    return GuestSessionStatus(ret)
  File "/usr/local/lib/python2.7/dist-packages/pyvbox-0.2.0-py2.7.egg/virtualbox/library_base.py", line 63, in __init__
    raise ValueError("Can not find enumeration where value=%s" % value)
ValueError: Can not find enumeration where value=None
```

**Comment by mjdorma** [comment]
I added a hacky three times check against the interface object (just incase xpcom was giving us a dodgy result).
