### ISSUE TITLE
take_snapshot failed

### ISSUE THREAD

**Issue by lookerson** [mjdorma/pyvbox#45]
Hello, I use IConsole.take_snapshot() to creates a new snapshot. But it is failed to find attribute takeSnapshot in <virtualbox.library_ext.console.IConsole object. 

My script is:

```
In [1]: import virtualbox

In [2]: vbox = virtualbox.VirtualBox()

In [3]: vm = vbox.find_machine('test')

In [4]: session = virtualbox.Session()

In [5]: progress = vm.launch_vm_process(session, 'gui', '')

In [6]: session.console.pause()

In [7]: session.console.take_snapshot('a', 'aaa')
```

And it is failed such as:

```
C:\Python27\lib\site-packages\virtualbox\library.pyc in take_snapshot(self, name, description)
  13200             raise TypeError("description can only be an instance of type basestring")
  13201         progress = self._call("takeSnapshot",
> 13202                      in_p=[name, description])
  13203         progress = IProgress(progress)
  13204         return progress

C:\Python27\lib\site-packages\virtualbox\library_base.pyc in _call(self, name, in_p)
    169     def _call(self, name, in_p=[]):
    170         global vbox_error
--> 171         method = self._search_attr(name)
    172         if inspect.isfunction(method) or inspect.ismethod(method):
    173             return self._call_method(method, in_p=in_p)

C:\Python27\lib\site-packages\virtualbox\library_base.pyc in _search_attr(self, name, prefix)
    150                 time.sleep(0.1)
    151         else:
--> 152             raise AttributeError("Failed to find attribute %s in %s" % (name, self))
    153         return attr
    154

AttributeError: Failed to find attribute takeSnapshot in <virtualbox.library_ext.console.IConsole object at 0x0000000004A479B0>
```

My Enviroment is:

```
+ Python 2.7.10 64bit
+ pyvbox 0.2.2
+ VirtualBox 5.0.10
+ Windows 10 x64
```

Can you help me? I don't know why I will be failed. Thank you. :)

**Comment by XayOn** [comment]
Same problem, python2.7, pyvbox==1.0.0 and virtualbox 4.3...
It was "working" with virtualbox 4.2 (except i got several segmentation faults, but that happened with VBoxManage manually too)

**Comment by SethMichaelLarson** [comment]
I was able to make this work with VirtualBox 5.1.14

**Comment by choman** [comment]
Using vbox 5.1.16 I get this error:

Traceback (most recent call last):
  File "./vboxvdi", line 148, in <module>
    mygo()
  File "./vboxvdi", line 119, in mygo
    m = virtualbox.library.IMachine.take_snapshot(a, "bob", "alsbndl", False)
  File "/usr/local/lib/python2.7/dist-packages/pyvbox-1.0.0-py2.7.egg/virtualbox/library.py", line 13101, in take_snapshot
    in_p=[name, description, pause])
  File "/usr/local/lib/python2.7/dist-packages/pyvbox-1.0.0-py2.7.egg/virtualbox/library_base.py", line 172, in _call
    return self._call_method(method, in_p=in_p)
  File "/usr/local/lib/python2.7/dist-packages/pyvbox-1.0.0-py2.7.egg/virtualbox/library_base.py", line 198, in _call_method
    raise errobj
virtualbox.library.OleErrorNotimpl: 0x80004001 (**Method takeSnapshot is not implemented**)

**Comment by choman** [comment]
OK I am officially past this above issue.  but I think there is another issue here,  the follow code

```
self.clone.lock_machine(self.session, self.LOCKTYPE)
x, p = self.session.machine.take_snapshot("test1", "test2", True)

self.logger.info("waiting... ")
p.wait_for_completion(timeout=-1)

```
produces this error
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./vboxvdi", line 288, in clone_vm
    self.take_snapshot()
  File "./vboxvdi", line 542, in take_snapshot
    p.wait_for_completion(timeout=-1)
  File "/usr/local/lib/python2.7/dist-packages/pyvbox-1.0.0-py2.7.egg/virtualbox/library_ext/progress.py", line 21, in wait_for_completion
    super(IProgress, self).wait_for_completion(timeout)
  File "/usr/local/lib/python2.7/dist-packages/pyvbox-1.0.0-py2.7.egg/virtualbox/library.py", line 19304, in wait_for_completion
    in_p=[timeout])
  File "/usr/local/lib/python2.7/dist-packages/pyvbox-1.0.0-py2.7.egg/virtualbox/library_base.py", line 170, in _call
    method = self._search_attr(name)
  File "/usr/local/lib/python2.7/dist-packages/pyvbox-1.0.0-py2.7.egg/virtualbox/library_base.py", line 151, in _search_attr
    raise AttributeError("Failed to find attribute %s in %s" % (name, self))
  File "/usr/local/lib/python2.7/dist-packages/pyvbox-1.0.0-py2.7.egg/virtualbox/library_ext/progress.py", line 16, in __str__
    return _progress_template % dict(o=self.operation, p=self.percent,
  File "/usr/local/lib/python2.7/dist-packages/pyvbox-1.0.0-py2.7.egg/virtualbox/library.py", line 19213, in operation
    ret = self._get_attr("operation")
  File "/usr/local/lib/python2.7/dist-packages/pyvbox-1.0.0-py2.7.egg/virtualbox/library_base.py", line 155, in _get_attr
    attr = self._search_attr(name, prefix='get')
  File "/usr/local/lib/python2.7/dist-packages/pyvbox-1.0.0-py2.7.egg/virtualbox/library_base.py", line 151, in _search_attr
    raise AttributeError("Failed to find attribute %s in %s" % (name, self))
  File "/usr/local/lib/python2.7/dist-packages/pyvbox-1.0.0-py2.7.egg/virtualbox/library_ext/progress.py", line 16, in __str__
    return _progress_template % dict(o=self.operation, p=self.percent,
  File "/usr/local/lib/python2.7/dist-packages/pyvbox-1.0.0-py2.7.egg/virtualbox/library.py", line 19213, in operation
    ret = self._get_attr("operation")
  File "/usr/local/lib/python2.7/dist-packages/pyvbox-1.0.0-py2.7.egg/virtualbox/library_base.py", line 155, in _get_attr
    attr = self._search_attr(name, prefix='get')
  File "/usr/local/lib/python2.7/dist-packages/pyvbox-1.0.0-py2.7.egg/virtualbox/library_base.py", line 151, in _search_attr
    raise AttributeError("Failed to find attribute %s in %s" % (name, self))
  File "/usr/local/lib/python2.7/dist-packages/pyvbox-1.0.0-py2.7.egg/virtualbox/library_ext/progress.py", line 16, in __str__
    return _progress_template % dict(o=self.operation, p=self.percent,
  File "/usr/local/lib/python2.7/dist-packages/pyvbox-1.0.0-py2.7.egg/virtualbox/library.py", line 19213, in operation
  ret = self._get_attr("operation")

```

This repeats for a while around the the last line as a reference point.  my current solution is to 
wrap the "p.wait_for_completion" call, such as


```
try:
     p.wait_for_completion(timeout--1)
except:
     pass

```

**Comment by SethMichaelLarson** [comment]
Glad that the first issue was solved, @choman.  Could you reopen the second issue as another issue?
